### ISSUE TITLE
Error when i choose export in the back-end

### ISSUE THREAD

**Issue by NiekDeelen** [magento-hackathon/FastSimpleExport#2]
About: magento-hackathon/FastSimpleExport

I have a problem, When i run the export i will get this error:
Entity adapter obejct must be an instance of Mage_ImportExport_Model_Export_Entity_Abstract

We are running: Magento ver. 1.9.3.4

Do you know how I can fix this?

Thanks!

**Comment by nhp** [comment]
This extension is not for export from the backend but from some kind of php script like shown in the examples of supported entities.

**Comment by NiekDeelen** [comment]
Hello,

 

Thanks for your quick reply!

 

A to bad, so why does it add an option to Config > import/export > Export:

 



 

What I want is an export of all my categories and the products that are in it. Eventually i want to make an feed with category links and name and price of an product, I can’t do that with this extension?

 

Because I also installed this extension:

https://github.com/avstudnitz/AvS_FastSimpleImport/tree/master

 

And there they say:

Importing of additional entities: Categories, Category-Product relations

 

So I thought if I install the exportversion, I could export my categorys and there relations.

 

Met vriendelijke groet,

 

Niek Deelen

Goedkoopprinten.nl

 



 

Van: Nils Preuß [mailto:notifications@github.com] 
Verzonden: woensdag 11 oktober 2017 16:51
Aan: magento-hackathon/FastSimpleExport <FastSimpleExport@noreply.github.com>
CC: NiekDeelen <niek@goedkoopprinten.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [magento-hackathon/FastSimpleExport] Error when i choose export in the back-end (#2)

 

This extension is not for export from the backend but from some kind of php script like shown in the examples of supported entities.

**Comment by pogster** [comment]
@nhp It's really not fully compatible to the core, when developer mode is on it will not work at all:

> Recoverable Error: Argument 1 passed to Mage_ImportExport_Model_Export_Entity_Abstract::setWriter() must be an instance of Mage_ImportExport_Model_Export_Adapter_Abstract, instance of MagentoHackathon_FastSimpleExport_Model_Export_Adapter_Array given, called in /var/www/html/app/code/community/MagentoHackathon/FastSimpleExport/Model/Export.php on line 68 and defined  in /var/www/html/app/code/core/Mage/ImportExport/Model/Export/Entity/Abstract.php on line 491
> 
> #0 /var/www/html/app/code/core/Mage/ImportExport/Model/Export/Entity/Abstract.php(491): mageCoreErrorHandler(4096, 'Argument 1 pass...', '/var/www/html/a...', 491, Array)
> #1 /var/www/html/app/code/community/MagentoHackathon/FastSimpleExport/Model/Export.php(68): Mage_ImportExport_Model_Export_Entity_Abstract->setWriter(Object(MagentoHackathon_FastSimpleExport_Model_Export_Adapter_Array))
> #2 /var/www/html/app/code/community/MagentoHackathon/FastSimpleExport/Model/Export.php(9): MagentoHackathon_FastSimpleExport_Model_Export->export()
> #3 /var/www/html/app/code/local/Gruenspar/Synchronization/Model/Export/Product/Export.php(274): MagentoHackathon_FastSimpleExport_Model_Export->processProductExport()
